package com.tk.learn.cloudgateway.audit;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;

/**
 * Domain model for route audit trail
 * Uses SimpleJdbcClient for CRUD operations (no JPA)
 * @Data is safe to use here since this is not a JPA entity
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RouteAudit {

    // Database column: audit_id
    // Auto-generated by database (IDENTITY)
    private Long auditId;

    // Database column: route_id
    private String routeId;

    // Database column: action
    // Values: CREATE, UPDATE, DELETE
    private String action;

    // Database column: version
    private Integer version;

    // Database column: created_by
    private String createdBy;

    // Database column: created_at
    private LocalDateTime createdAt;

    // Database column: old_value
    // Stores JSON representation of previous state
    private String oldValue;

    // Database column: new_value
    // Stores JSON representation of new state
    private String newValue;

    // Database column: description
    private String description;
}

